### ISSUE TITLE
改进建议：将任意按键作为修饰键

### ISSUE THREAD

**Issue by Aqaao** [cataerogong/keymap#10]
[shortcutmapper](https://github.com/waldobronchart/ShortcutMapper)有这个功能。
对于用ahk或者kanata之类的软件映射按键的使用者有用。

**Comment by cataerogong** [comment]
【键谱】支持自定义修饰键，在设置中可以将任意键设置为修饰键：

![image](https://github.com/cataerogong/keymap/assets/54147585/90977329-45a4-444f-b8d8-d31620c5ee18)

在【帮助】的【2.进阶技巧】里也提到了：

![image](https://github.com/cataerogong/keymap/assets/54147585/7e455456-3ae4-4382-9f8c-413f5dff830e)

使用中如果还有其他问题或者建议，欢迎随时提 issue
