### ISSUE TITLE
这个工具不错，想提几点建议希望采纳

### ISSUE THREAD

**Issue by sunny-00001** [cataerogong/keymap#2]
1.建议将数据选项卡与键表选项卡左对齐，避免鼠标切换距离过长
2.希望键层可以自定义名称
3.希望在左侧增加一列“引导键”或者“修饰键”，分别为全部、Ctrl、Shift、Alt、RCtrl、RShift、RAlt、Win，增加一个加号，功能是添加修饰符，可以是任意按键，默认选择全部，即目前的模式，可选任意修饰符或多选，对应不同键图、键表
4.希望在键表层增加筛选功能

**Comment by cataerogong** [comment]
1 已经改成全部靠右了
2 有网友已经完成这个功能，但 PR 还没有合进来
3是说自定义修饰键吗？
4 没太理解

马上会发布新版本了，等看看？

**Comment by sunny-00001** [comment]
第三条，现在仅支持系统默认的修饰键，要是能支持自定义修饰键就好了，另外就是增加修饰键列，直接在键帽上显示提示，就像这样。点击Ctrl，仅显示Ctrl键有关的快捷键提示，再次点击显示全部快捷键提示。在点击Ctrl时再点击Shift，仅显示与Ctrl+Shift有关的快捷键提示，以此类推，相当于进行分类。
![图片](https://github.com/cataerogong/keymap/assets/28869215/749f9175-7486-427c-b52b-86851a2b84ce)
第四条，快捷键提示太多，就很难找到。所以建议这里增加筛选框
![图片](https://github.com/cataerogong/keymap/assets/28869215/d6f2dda6-badb-47eb-9f80-7bb43b04c6b7)
