### ISSUE TITLE
可否为按键增加一个属性"颜色", 并且关联到键表的按键颜色的显示, 让键表可以按照颜色分组显示. 

### ISSUE THREAD

**Issue by rsyqvthv** [cataerogong/keymap#4]
如下图: 

每个按键有个颜色属性, 相当于一个分类, 并且为这个分类加一个名称. 
在键表中, 按照颜色进行分组显示(图中未做展示, 仅展示了颜色映射)
我想这样可以在不增加"层"的情况下, 一目了然的了解快捷键的布局, 也对庞杂的键表有所分类, 便于记忆. 

希望您能考虑我的建议. 感谢你.

![Untitled-1](https://github.com/cataerogong/keymap/assets/2230369/a7f8fc89-41a9-4219-8f44-3bb6eaa96417)

**Comment by cataerogong** [comment]
嗯，我先记下了。

探讨一下，一个主键上有多个组合键，那这个颜色是跟随主键吗？只要同一个主键的组合键，颜色都一样？

**Comment by rsyqvthv** [comment]
> 嗯，我先记下了。

感谢.

> 探讨一下，一个主键上有多个组合键，那这个颜色是跟随主键吗？只要同一个主键的组合键，颜色都一样？

我不了解这样实施的复杂性, 我仅仅按照我的想法说说, 有太奢望的地方请您包涵.

如果颜色(分类)只能跟随主键, 
那么这时对于主键的不同功能键(shift, ctrl, alt)的组合会产生分类不一致的问题. 
比如上图中的例子, 
i 和 o 本来是一类的, 但是ctrl+i的功能和他们不同, 最好是可以分开的. 

所以我想, 也许不光主键有颜色属性, 所有和功能键的组合也都应该有颜色属性, 
这样可能更符合需要. 

如果是这样的话, 颜色会影响下面的一些已有的功能: 

- 首先, 是键表. 到时候键表可能除了按照颜色分组不同的按键之外, 如果加上可以在键表中通过拖拽的方式改变按键的颜色分类会极大的增加定义的效率, 也比进入主键>再找功能键组合> 再定义颜色这样要更方便一些. 
- 然后, 键表中显示的分类, 请务必加一个"未定义颜色"的分类, 如果没有这个分类, 我们也许会对自己定义颜色的完整性有持续的焦虑. :)
- 对于有多个颜色的键, 在键帽上的颜色显示可能有所考虑, 但我想只提示一下此键有不同的颜色就好, 颜色显示仍然按照主键的来, 并不需要面面俱到, 不然, 一来会让键盘显得颜色杂乱, 二来真正的分类显示都在键表中, 没有必要在键帽上再做一次展示. 
- 关于"键盘层", 我不大理解当初设计这个功能的初衷. 但我想如果加入颜色, 也许可以让颜色和层有某种合并. (未想好)

以上就是我能想到的和颜色相关的事宜, 请参详.

**Comment by cataerogong** [comment]
哇，好大一篇 😄 
谢谢你写得这么详细，我会好好考虑颜色这个功能的。
对于多个组合键，我是这么考虑的：如果每个组合键都可以定义颜色，那每个按键上本来就有主映射（就是主组合键），那就用这个组合键的颜色好了
键盘层，是有人提出来，有些定制化键盘上有开关，可以切换按键编码，一个键在不同的开关状态下可以变成完全不同的键

**Comment by rsyqvthv** [comment]
> 对于多个组合键，我是这么考虑的：如果每个组合键都可以定义颜色，那每个按键上本来就有主映射（就是主组合键），那就用这个组合键的颜色好了

如果你是指"键帽"显示色而言, 我也觉得用"主键"颜色就足够了(加*的键)
(也就是我上面说的"影响已有功能"中的第三点)
但可否在这种有多个不同颜色的键下做个不枪眼的标记, 比如: 
键帽上主要显示的是主键颜色(例子中是橘黄色), 
右下角有个角标(是未定义颜色的键帽颜色, 灰色), 
其中的数字4, 代表其中包含几个颜色分类. (和组合键个数不同)

<img width="194" alt="20240117_064252" src="https://github.com/cataerogong/keymap/assets/2230369/11ef6345-8f6b-4790-85ee-2bafd3fb537b">

:)

> 键盘层，是有人提出来，有些定制化键盘上有开关，可以切换按键编码，一个键在不同的开关状态下可以变成完全不同的键

感谢你的解释, 
我想和我以前理解的键盘层的意思是一样的. 
其实, 即便是普通的(非定制)键盘都有"键盘层"的概念, 
就是功能键(ctrl, shift之类的). 
比如: 当我们按下shift, 再按其他按键, 编码就不同了. 

所以这是我一直觉得键盘层在keymap中可能有些重复, 且不直观的原因. 
我想, 如果您考虑引用颜色分类系统的话, 
这也是个机会简化和直观化"键盘层"的机会. 

我的设想是, 
(这个有些复杂, 希望你不介意我尽量详细的描述 :) )
将键盘层融入到按键的本来操作中, 
用"修改键"(Modifier keys)的概念替代键盘层. 
修改键包括: ctrl, shift, alt, capkey 和 任何可以自定义的键.

如果引入修改键的话, 可能会涉及其他已有功能的改变: 

- 按键定义时, 多一个选项: "是否将本键用作修改键", 默认情况下, ctrl, shift之类的按键这个选项是勾选的.(但保留可以取消的可能). 
- 和我们的按键操作的习惯是一致的是:当我们在keymap中, 按下shift键后, (触发键盘层切换), 这时按键上仅显示和shift组合的快捷键. 将键盘层融入到我们习惯的操作中.
- 对于sublime text这样可以将 `ctrl+k` 作为修改键的软件来说(如下图1), 我们也能通过修改键定义的方式来描述它的操作: 比如sublime text中, 先按`ctrl+k` 然后按住 `ctrl` 不放, 再按 `up`, 可以触发一个功能, 那么我们在keymap中就可以先定义 `ctrl+k` 为修改键, 这时, 我们再选 `up`键的时候, 除了常规的 ctrl shift alt这些常规修改键之外, 还多一个 `ctrl+k`.
- 那么如何能直观的了解自己都定义了哪些修改键呢? 没错, 我们的颜色分类系统能很好的解决这个难题. 我们可以专门有一类: 修改键. 其下罗列出的键值, 比如ctrl或者是我们自定义的 `ctrl+k`. 而且这些键值是可以点击, 触发相应的层显示的.
- 那么如果我的修改键不在默认的键盘中怎么办? 这可能需要我们允许大家可以自定义几个单独的按键. 我设想可以在键盘某处加一个"增加修改键"的功能(不是按键)(如下图2). 用这个功能增加的键"只"会出现在键表中, 并且有个稍微不同的着重的显示, 比如标准键 的外框是兰色的, 这种自定的外框是黑色的. (如下图3)

<img width="440" alt="20240117_070739" src="https://github.com/cataerogong/keymap/assets/2230369/518eb0f5-1d10-4a80-8a70-422a86e07056">

<img width="525" alt="20240117_072456" src="https://github.com/cataerogong/keymap/assets/2230369/2abf9ef6-121a-4e72-ad06-0c847bdcd17b">

<img width="476" alt="20240117_072832" src="https://github.com/cataerogong/keymap/assets/2230369/f3132df2-2135-44e4-b30a-d0fafa3d9ede">

抱歉对于键盘层扩展了这么多, 
但如果你仔细了解这种改变, 
我想可能是对keymap的某种简化, 
也因为这种简化, 让keymap有更多的兼容性, 
且在直观和直觉操作方面更进一步. 

希望keymap能更加完美. 


:)

**Comment by cataerogong** [comment]
我在写键谱时，也思考过这种多次连续按键的问题，以下是我的想法：
键谱只针对记录“组合键”，“组合键”的概念是“同时按下的多个键(+)”，对于像sublime text这样的（Ctrl+K，Ctrl+Up）我觉得应该叫“连续键(,)”（借用格斗游戏里的连续技），它恰恰契合了键盘层的理念：按下连续键的起始键（Ctrl+K）后，后续整个键盘的按键所对应的功能完全不一样了；类似的，vi 的 esc 也可以算是连续键的起始键，按完后进入命令层，后续键盘输入虽然键值不变，但是功能变了；windows 程序的菜单也可以算，Alt+F 进入“File 功能键盘层”（打开 File 菜单），然后 O 键的功能就是打开文件，没有对应功能的按键则被忽略。
这其实是应对键盘上按键不够、功能太多的两个思路，并且经常结合起来，最常用的功能用组合键——更快，其他的用连续键——按键选择余地更多，而且可以更好地组织、分层，便于整理、记忆。
对于连续键、物理键盘层（现在也有软件实现的键盘层），起始键/切换键按下后，就不用再关注这个键了，而只需要关注之后真正调用功能的组合键，因此我觉得，应该把以这个起始键开始的连续键后续的组合键都放到一个键盘层下，这个起始键应该体现在层名里，而不需要体现在键表里。
所以这是我对当初引入键盘层的思考，当然，怎么使用是别人的事了，用出花来也是可能的（已经用出花来了，小众论坛上有人用扩展键布局来画“鼠标手势分布图” :-D
其实，我一直有些头痛的点是，在同一层下，组合键实在太多，颜色分类就很不好搞，搞颜色分类，最好是一个键上的组合键是可以分到一类的，否则这个键的颜色就不能代表它上面的所有组合键。对于这种快捷键多得一批的应用，我个人是觉得还是要分多个层来组织。

其实还有一种，超过2个的连续键，比如 CS 里的 B43，嗯，完全不建议在当前的键谱里搞，想着就…… 😹

**Comment by rsyqvthv** [comment]
抱歉这么晚回复您, 

感谢你提及了这么多的按键方式, 我也学到很多. 
我相信您已经考虑了很多的因素, 并且我也看到了您最新的beta版本增加了颜色. 

我还在体会颜色的使用. 

希望keymap能越来越好. 
再次感谢您提供的这个工具.

**Comment by cataerogong** [comment]
有用就好 😸 试试最新版，不用 exe 就可以存取 .keymap 文件了
你应该不是小众论坛的吧，这个项目的起源是小众论坛上网友的一个需求，写着玩的，没想到还有不少人用上了 😄
欢迎来小众玩 [meta.appinn.net](https://meta.appinn.net)
