### ISSUE TITLE
个人的一些改进细节望采纳

### ISSUE THREAD

**Issue by sunny-00001** [cataerogong/keymap#6]
1.建议在键图模式侧栏增加修饰键和扩展键筛选
2.建议在键表模式增加二级分组即分组依据，比如按菜单分组，分为文件、编辑、视图、设置、窗口、帮助；按功能分组，分为编辑、缩放、旋转、选择、关闭、打开、跳转等

**Comment by cataerogong** [comment]
> 1.建议在键图模式侧栏增加修饰键和扩展键筛选

现在键图上可以右键点击修饰键进行筛选，按住Ctrl可以多选，在键表顶部直接有筛选栏。

> 2.建议在键表模式增加二级分组即分组依据，比如按菜单分组，分为文件、编辑、视图、设置、窗口、帮助；按功能分组，分为编辑、缩放、旋转、选择、关闭、打开、跳转等

这感觉就是把分组变成标签，一个快捷键可以有多个标签。
暂时还没有这个改动计划，我会把这个先记下来。

感谢你的建议！
