### ISSUE TITLE
有交流群吗

### ISSUE THREAD

**Issue by tongnixcv** [cataerogong/keymap#7]
这么方便的软件，有官方的交流群就好了
QQ微信或者电报均可

**Comment by cataerogong** [comment]
没有呢 😹 
我这个应用起因是小众论坛上的一个网友的需求，所以主要的交流都在那边的一个[帖子](https://meta.appinn.net/t/topic/50925)，欢迎到那边交流（说不定还能有其他收获
以后说不定会建个群什么的，看吧

**Comment by lhj5426** [comment]
> 没有呢 😹 我这个应用起因是小众论坛上的一个网友的需求，所以主要的交流都在那边的一个[帖子](https://meta.appinn.net/t/topic/50925)* ，欢迎到那边交流（说不定还能有其他收获 以后说不定会建个群什么的，看吧

哈哈 除了 看郭德纲 之外 我还是第一次看到 有人用 “看吧” 这个词

**Comment by cataerogong** [comment]
> 哈哈 除了 看郭德纲 之外 我还是第一次看到 有人用 “看吧” 这个词

看（情况）吧

想着说“走着瞧”好像不太对 🤣
