### ISSUE TITLE
建议合并「键谱」、「谱匣」和「谱匣」的辅助增强程序

### ISSUE THREAD

**Issue by ghost** [cataerogong/keymap#8]
原因一：三者占用空间极小，合并三者不会额外占用多少空间
原因二：三者常搭配使用，拆开三者会徒增烦恼
原因三：「键谱」将数据存储在浏览器本地，更换浏览器、退出账户等常见操作皆有可能让用户不慎清除数据
原因四：合并三者，用户无需下载另外的组件就可以通过资源管理器管理和备份数据

**Comment by cataerogong** [comment]
嗯，我会考虑把发布包合并成一个，再更新一下介绍文字。
