### ISSUE TITLE
点删除没反应

### ISSUE THREAD

**Issue by showyourlucky** [cataerogong/keymap#9]
如果用html打开, 删除是可以的, 但是exe打开就不能删除, 只能保存

https://github.com/cataerogong/keymap/assets/40224144/b52d975c-4f4c-46b1-9092-f8a86423e3fc

**Comment by cataerogong** [comment]
点击“删除”应该会弹一个确认框出来，感觉是弹不出来导致删除不了，是不是有啥禁止了？我用的是 js 的 confirm() 函数，应该不会被禁止吧（我电脑上重现不了

如果找不到原因，那等我过两天把 alert 和 confirm 改成自己实现的弹出框吧

**Comment by showyourlucky** [comment]
> 点击“删除”应该会弹一个确认框出来，感觉是弹不出来导致删除不了，是不是有啥禁止了？我用的是 js 的 confirm() 函数，应该不会被禁止吧（我电脑上重现不了
> 
> 如果找不到原因，那等我过两天把 alert 和 confirm 改成自己实现的弹出框吧

这个和浏览器或者ahk版本有关系吗, 我用keymap.html打开是可以删除的, 没搞清楚html新建的键谱保存在哪

![image](https://github.com/cataerogong/keymap/assets/40224144/c72e1ae0-b4cf-453b-8f98-1389664a4a01)

**Comment by showyourlucky** [comment]
重启了下电脑, 很神奇的好了

**Comment by cataerogong** [comment]
> 没搞清楚html新建的键谱保存在哪

html 的键谱保存在浏览器的缓存里，可以通过“保存”按钮下载成 `.keymap` 文件，也可以“打开” `.keymap` 文件，或者直接拖进页面来打开
